Repository Barbe-Bleue/vagSpaceX, pull requests merged in 2018-06, with the labels that each got.

#8 #1 company data api
  src/app/app.module.ts
  src/app/components/company-info/company-info.component.css
  src/app/components/company-info/company-info.component.html
  src/app/components/company-info/company-info.component.spec.ts
  src/app/components/company-info/company-info.component.ts
  src/app/models/CompanyInfo.ts
  src/app/modules/app-routing/app-routing.module.spec.ts
  src/app/modules/app-routing/app-routing.module.ts
  src/app/modules/shared/shared.module.spec.ts
  src/app/modules/shared/shared.module.ts
  src/app/providers/backend/company/company.service.spec.ts
  src/app/providers/backend/company/company.service.ts
  src/app/providers/backend/spacex-api.service.spec.ts
  src/app/providers/backend/spacex-api.service.ts
  src/app/typings/ServiceError.d.ts
  src/tslint.json
Labels: enhancement

#9 #2 rocket data api
  src/app/components/rocket-list/rocket-list.component.css
  src/app/components/rocket-list/rocket-list.component.html
  src/app/components/rocket-list/rocket-list.component.spec.ts
  src/app/components/rocket-list/rocket-list.component.ts
  src/app/models/Rocket.ts
  src/app/modules/app-routing/app-routing.module.ts
  src/app/providers/backend/rocket/rocket.service.spec.ts
  src/app/providers/backend/rocket/rocket.service.ts
Labels: enhancement

#13 #12 Fix le bordel je parle en franglais lol
  src/app/app.module.ts
  src/app/pipes/hugeNumber.pipe.ts
Labels: Fix

#16 #4 launchpad data api
  src/app/app.module.ts
  src/app/components/launchpad-list/launchpad-list.component.css
  src/app/components/launchpad-list/launchpad-list.component.html
  src/app/components/launchpad-list/launchpad-list.component.spec.ts
  src/app/components/launchpad-list/launchpad-list.component.ts
  src/app/components/launchpad/launchpad.component.css
  src/app/components/launchpad/launchpad.component.html
  src/app/components/launchpad/launchpad.component.spec.ts
  src/app/components/launchpad/launchpad.component.ts
  src/app/models/Launchpad.ts
  src/app/modules/app-routing/app-routing.module.ts
  src/app/providers/backend/launchpad/launchpad.service.spec.ts
  src/app/providers/backend/launchpad/launchpad.service.ts
Labels: enhancement

#18 #3 capsule data api
  src/app/app.module.ts
  src/app/components/capsule/capsule.component.css
  src/app/components/capsule/capsule.component.html
  src/app/components/capsule/capsule.component.spec.ts
  src/app/components/capsule/capsule.component.ts
  src/app/components/capsules-list/capsules-list.component.css
  src/app/components/capsules-list/capsules-list.component.html
  src/app/components/capsules-list/capsules-list.component.spec.ts
  src/app/components/capsules-list/capsules-list.component.ts
  src/app/models/Capsule.ts
  src/app/models/DetailedCapsule.ts
  src/app/providers/backend/capsule/capsule.service.spec.ts
  src/app/providers/backend/capsule/capsule.service.ts
Labels: enhancement

#22 #7 Fix an issue regarding the import of some modules
  src/app/app.module.ts
  src/app/models/DetailedCore.ts
Labels: Fix

#23 #6 add The api 4 detailed capsule
  src/app - Raccourci.lnk
  src/app/app.module.ts
  src/app/components/detailedcapsule/detailedcapsule.component.css
  src/app/components/detailedcapsule/detailedcapsule.component.html
  src/app/components/detailedcapsule/detailedcapsule.component.spec.ts
  src/app/components/detailedcapsule/detailedcapsule.component.ts
  src/app/components/detailedcapsules-list/detailedcapsules-list.component.css
  src/app/components/detailedcapsules-list/detailedcapsules-list.component.html
  src/app/components/detailedcapsules-list/detailedcapsules-list.component.spec.ts
  src/app/components/detailedcapsules-list/detailedcapsules-list.component.ts
  src/app/modules/app-routing/app-routing.module.ts
  src/app/providers/backend/detailedcapsule/detailedcapsule.service.spec.ts
  src/app/providers/backend/detailedcapsule/detailedcapsule.service.ts
Labels: enhancement

#28 Countdown
  src/app/components/capsule/capsule.component.html
  src/app/components/capsules-list/capsules-list.component.html
  src/app/components/capsules-list/capsules-list.component.spec.ts
  src/app/components/capsules-list/capsules-list.component.ts
  src/app/components/detailedcapsules-list/detailedcapsules-list.component.html
  src/app/components/launches-home/launches-home.component.html
  src/app/components/launches-home/launches-home.component.ts
  src/app/components/launchpad/launchpad.component.html
  src/app/components/launchpad/launchpad.component.ts
  src/app/components/rocket-list/rocket-list.component.css
  src/app/components/rocket-list/rocket-list.component.html
  src/app/modules/app-routing/app-routing.module.ts
Labels: Fix, enhancement

#29 Add a map for the launchpads
  src/app/components/launchpad/launchpad.component.html
  src/app/components/launchpad/launchpad.component.ts
  src/app/components/rocket-list/rocket-list.component.html
Labels: enhancement

#30 Countdown
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/launches-home/launches-home.component.html
  src/app/components/launches-home/launches-home.component.ts
Labels: enhancement
